# Generated by Django 5.2.7 on 2025-11-15 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reception', '0003_waitinglist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('pulse_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting Triage'), ('in_progress', 'In Progress'), ('done', 'Triage Complete'), ('sent_to_doctor', 'Sent to Doctor')], default='awaiting', max_length=20)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_triage', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient')),
            ],
            options={
                'ordering': ['-date_taken'],
            },
        ),
    ]
