# Generated by Django 5.2.7 on 2025-11-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Consultation', 'verbose_name_plural': 'Consultations'},
        ),
        migrations.AlterModelOptions(
            name='labrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='labrequest',
            old_name='date_requested',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='date_prescribed',
            new_name='created_at',
        ),
    ]
