# Generated by Django 5.2.7 on 2025-11-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_consultation_options_alter_labrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
